import './globals.css';
import type { Metadata } from 'next';
import { Nanum_Gothic } from 'next/font/google';
import Link from 'next/link';

const nanum_gothic = Nanum_Gothic({
  weight: ['400', '700'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Park Su-a Blog',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='ko'>
      <body className={nanum_gothic.className}>
        <header>
          <nav>
            <Link href='/'>Home</Link>
            <Link href='/posts'>Post</Link>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
